### ISSUE TITLE
Client Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by superdeen** [hahwul/dalfox#100]
Making use of dalfox always return this error: [E] not running Get https://site.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers) but this does not occur if I run it over vulnerable labs (site). How do I fix this?
Perhaps I need to add an header? what would it look like?

**Comment by superdeen** [comment]
Thanks for the tip, but then it gave same result; 
Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
[*] Using single target mode
[*] Target URL: https://www.superdrug.com/blog/?p=26929
[E] not running Get https://www.superdrug.com/blog/?p=26929: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
It was installed using go-get
Using OS
URL: https://superdrug.com/blog/?p=26929

Every other standard URL I tried gave same error output except if the URL is a link from an xss lab.

**Comment by hahwul** [comment]
Hello again @superdeen ,

I checked a few things based on the information you gave me. First of all, I found a feature(akamaighost) of the site and a bug of the dalfox.
## TL;DR

This site identifies non-browser client based on User-Agent and only 301(to www.superdrug.com). So you need to change the redirects options with `--follow-redirects`.  there's a UA verification on this site, and I found a small bug in the code of dalfox. After upgrading and scanning, as shown below, you will have normal browser's user-agent.

```shell
# update dalfox
$ go get -u github.com/hahwul/dalfox

# using add User-Agent header, testing this site
$ dalfox url https://superdrug.com/blog/\?q\=333 --follow-redirects
```

Before

| Process in code    | Default UA                                                   | Support Custom UA |
| ------------------ | ------------------------------------------------------------ | ----------------- |
| Health check (bug) | Go-http-client/1.1                                           | X                 |
| Parameter Analysis | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0 | O                 |
| Scanning           | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0 | O                 |

After

| Process in code    | Default UA                                                   | Support Custom UA |
| ------------------ | ------------------------------------------------------------ | ----------------- |
| Health check  | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0 | O                 |
| Parameter Analysis | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0 | O                 |
| Scanning           | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0 | O                 |


## Testing data

I checked error on my env

```
[*] Target URL: https://superdrug.com/blog/?q=333
[E] not running Get https://superdrug.com/blog/?q=333: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

testing curl, but 403
```
$ curl -i -k https://superdrug.com/blog/\?q\=333
HTTP/2 403
server: AkamaiGHost
mime-version: 1.0
content-type: text/html
content-length: 271
...

<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;superdrug&#46;com&#47;blog&#47;&#63;" on this server.<P>
Reference&#32;&#35;18&#46;4ad2c17&#46;1598405703&#46;628c137
</BODY>
</HTML>
```

when add browser ua, 301

```
$ curl -i -k https://superdrug.com/blog/\?q\=333 -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
HTTP/2 301
server: Apache
x-frame-options: SAMEORIGIN
location: http://www.superdrug.com/blog/?q=333
```

## Bug

but, header base options not working default logic 

```
$ dalfox url https://superdrug.com/blog/\?q\=333 --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" --proxy http://localhost:8080
```

in BurpSuite (health check req)
```
GET /blog/?q=333 HTTP/1.1
Host: www.superdrug.com
User-Agent: Go-http-client/1.1       # bug!
Accept-Encoding: gzip, deflate
Connection: close

```

Since you installed it as go get, please update it through go get again!

```
$ go get -u github.com/hahwul/dalfox
```

Now that the release script is running, the release of `homebrew`/`snapcraft` will be updated soon 😎

**Comment by hahwul** [comment]
@superdeen 
And because that site blocks fast requests, I think we need a proper delay option.

```
$ dalfox version

    _..._
  .' .::::.   __   _   _    ___ _ __ __
 :  :::::::: |  \ / \ | |  | __/ \\ V /
 :  :::::::: | o ) o || |_ | _( o )) (
 '. '::::::' |__/|_n_||___||_| \_//_n_\
   '-.::''

Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
v2.0.2
```

```shell
$ dalfox url https://www.superdrug.com/blog/\?q\=333 --delay 1000

    _..._
  .' .::::.   __   _   _    ___ _ __ __
 :  :::::::: |  \ / \ | |  | __/ \\ V /
 :  :::::::: | o ) o || |_ | _( o )) (
 '. '::::::' |__/|_n_||___||_| \_//_n_\
   '-.::''

Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. @hahwul
[*] Using single target mode
[*] Target URL: https://www.superdrug.com/blog/?q=333
[*] Vaild target [ code:200 / size:136299 ]
[*] Start parameter analysis.. 🔍
[*] Start static analysis.. 🔍
[I] Access-Control-Allow-Origin is https://www-wp-sd.uk.aswatson.net
[I] Content-Type is text/html;charset=UTF-8
[I] Content-Security-Policy is default-src 'self' https://*.visa.com https://*.goinstore.com; object-src 'self' blob: https://*.visa.com https://*.doubleclick.net https://*.hotjar.com https://*.bazaarvoice.com https://*.worldpay.com; frame-src 'self' blob: https://h.online-metrix.net https://*.visa.com https://*.superdrug.com https://*.doubleclick.net https://*.hotjar.com https://*.bazaarvoice.com https://*.worldpay.c
... snip ...

[W] BypassCSP: .doubleclick.net .googleadservices.com *.google.com *googleapis.com
    Needs manual testing. please refer to it. https://t.co/lElLxtainw?amp=1
[I] X-Frame-Options is SAMEORIGIN
[I] Strict-Transport-Security is max-age=63072000;includeSubDomains;preload
[I] Reflected q param => inHTML[1]
    1540 line:   value="/blog/?q=333DalFox" />      </form></div><
[*] Generate XSS payload and optimization.Optimization.. 🛠
[*] Start XSS Scanning.. with 289 queries 🗡
 ◢  Queries(14 / 289) :: Testing "q" param with 100 worker
```

**Comment by superdeen** [comment]
Thanks! 
All is good and fine  now at my end.

**Comment by hahwul** [comment]
@superdeen cool!! And I will close this issue

Cheers!
