### ISSUE TITLE
Add a flag to stop after first hit

### ISSUE THREAD

**Issue by marcelo321** [hahwul/dalfox#115]
Hello,

Would be cool to add a flag so it stops and goes to next url or command after finding something. Sometimes once PoC is enough and we don't need 10 of them.

**Comment by hahwul** [comment]
Hi @marcelo321 
Yes, if find one currently valid PoC(Verified DOM), dalfox stop this param of url. (There's a list in the job queue that looks like scanning, but if you look at the logs and traffic, it's not processed.)

![1414](https://user-images.githubusercontent.com/13212227/93033147-fdea1280-f66f-11ea-853b-607abcbdf5ae.png)

So even if I scan this page, don't see many results. If dalfox show all valid PoCs are represented, there should be a lot of results.

![1415](https://user-images.githubusercontent.com/13212227/93033264-78b32d80-f670-11ea-8442-7329fde869a2.png)

I would like to support the suspension immediately, but so far, passing has been the best option due to the concurrency of go. If you have a good idea, please share it.
