### ISSUE TITLE
what's mean by dalfox-authorization-basic ? 

### ISSUE THREAD

**Issue by nagarajcruze** [hahwul/dalfox#142]
![dalfox-authorization-basic](https://user-images.githubusercontent.com/32562272/98366111-75796400-2059-11eb-9a2c-b2b5c481b6d4.png)

**Comment by hahwul** [comment]
@Hi @nagarajcruze 
Hello! That is, Grepping detection is data detected according to the regular expression in Response. I'm going to try to reduce the pattern because I've been getting a lot of inquiries about Otam lately! Refer to the code below!

https://github.com/hahwul/dalfox/blob/master/pkg/scanning/grep.go#L20

**Comment by nagarajcruze** [comment]
oh i got you, so in my screenshot everything is false positive, right?

**Comment by hahwul** [comment]
@nagarajcruze 
Right, the detected content looks like a false positive. It would be nice to remove the basic auth rule too.
I currently fixing a bug and will be released soon. I will reduce the regex pattern that seems unnecessary in 2.2.3. Please note!
