### ISSUE TITLE
Detect CRLF vulnerability

### ISSUE THREAD

**Issue by shelld3v** [hahwul/dalfox#227]

**Comment by hahwul** [comment]
Thank you for your feature opinion. I'll make it to be added to the BAV. but It may not be easy to check the response header based CLRF (logic only looks at the body in now. Because it's an XSS tool)

This is what BAV is like this.
* https://github.com/hahwul/dalfox/pull/119
* https://github.com/hahwul/dalfox/pull/122

**Comment by hahwul** [comment]
Added it! from now on, dalfox can detect through Grepping if a CRLF Injection detection header in the response header.

```
[*] 🦊 Start scan [SID:Single] / URL: http://localhost:8070/xss/abcd/2
[G] Found CRLF Injection via built-in grepping / original request
[POC][G][CRLF/GET] http://localhost:8070/xss/abcd/2
[I] Found 0 testing point in DOM base parameter mining
[I] Content-Type is text/html; charset=UTF-8is 🔍 
[I] Reflected PATH '/xss/dalfoxpathtest/2' => Injected: /inJS-single(1)]
[V] Triggered XSS Payload (found dialog in headless)aiting headless 
[POC][V][GET] http://localhost:8070/xss/abcd'-confirm(1)-'/2?=
```
