### ISSUE TITLE
add ssrf

### ISSUE THREAD

**Issue by Kalimon12** [hahwul/dalfox#256]
https://burpcollaborator.net

**Comment by hahwul** [comment]
Hi @Kalimon12 
First, thank you for submit feature reqeust :D
I don't know if it's possible with BAV, but I'll try to add it. 
If add it, it will be applied in a similar form to blind xss.

**Comment by hahwul** [comment]
Unfortunately, BAV-SSRF will end the issue spec-out. Because SSRF seems to be too big an attack vector to test with BAV. 

It can directly affect scan performance, and detection verification requires interaction with other tools, such as interactsh, oast, burp collaborator, which will hinder scanning of the original purpose of xss quickly and accurately.

I think SSRF should configure a separate tool for SSRF.

Enjoy rest of the day!
Thank you
