### ISSUE TITLE
"Severity" field addition to JSON output

### ISSUE THREAD

**Issue by HarryJohnAsir** [hahwul/dalfox#323]
It would be really helpful if we could have "Severity" added to the JSON output. 

Based on the issue severity, Severity field can have value as below.
1. Info
2. Low
3. Medium
4. Major
5. Critical

Reference: JSON Output additions #261

**Comment by hahwul** [comment]
@HarryJohnAsir 
Thank you for your opinion! 
Dalfox is mostly for checking XSS, so I'm not sure if I can set and include the Severity, but I'll give it a try :D

**Comment by hahwul** [comment]
In order to simplify and output Severity, I would like to mark it as `Low`/`Medium`/`High` by referring to the OWASP Risk Rating and CVSSv3. 

* https://owasp.org/www-community/OWASP_Risk_Rating_Methodology
* https://www.first.org/cvss/specification-document

| Severity | Attribute                                                    |
| -------- | ------------------------------------------------------------ |
| Low      | - BuiltIn-Grep                                               |
| Medium   | - XSS (Reflected payload)<br />- BAV-CRLF<br />- BAV-SQLi (SQL Error)<br />- BAV-OpenRedirect |
| High     | * XSS (Verified payload) <br />- BAV-SSTI                    |

*Dalfox's severity (not fixed yet.)*

In fact, XSS is not reported critically in CVSS, etc. In particular, I think there is a limitation in the risk grade because the a scanner cannot create an Exploit chain.

**Comment by HarryJohnAsir** [comment]
Thank you.

**Comment by hahwul** [comment]
## Test 
![Screenshot_20211217_222402](https://user-images.githubusercontent.com/13212227/146551152-f5201db1-0179-45da-ba33-d0eac8628a52.png)

**Comment by hahwul** [comment]
@HarryJohnAsir 
Close the issue by adding the function. It's going to be released on v2.6.3. If there's nothing special, I think it'll be released this weekend!

Thank you :D

**Comment by HarryJohnAsir** [comment]
Thank you
