### ISSUE TITLE
segmentation violation exception

### ISSUE THREAD

**Issue by ceylanb** [hahwul/dalfox#57]
The command:
`echo "https://xss-game.appspot.com/level1/frame?query=test" | dalfox pipe -blind https://<test>.xss.ht -o result.txt`

```
[*] Using pipeline mode
[*] Loaded 1 target urls
[*] Target URL: https://xss-game.appspot.com/level1/frame?query=test
[*] Vaild target [ code:200 / size:400 ]
[*] Start static analysis.. 🔍
[*] Start parameter analysis.. 🔍
 ◓  Waiting routines.. panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x785a29]

goroutine 11 [running]:
github.com/hahwul/dalfox/pkg/scanning.StaticAnalysis(0xc0000281c0, 0x34, 0xc0001093e0, 0x1c)
        /home/b0dy/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:424 +0x89
github.com/hahwul/dalfox/pkg/scanning.Scan.func1(0xc000024970, 0xc0001093e0, 0xc0000281c0, 0x34, 0xc0000100a8)
        /home/b0dy/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:74 +0xa3
created by github.com/hahwul/dalfox/pkg/scanning.Scan
        /home/b0dy/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:71 +0x358

```

**Comment by hahwul** [comment]
Well, I tested it, and I'm not having any problems. Would you like to update it to the latest version first and test it?

```
go get -u github.com/hahwul/dalfox
```

If my guess is right, it's thought to be a source before adding a defense code. If the current latest version has the same problem, i need a little more information for a detailed analysis.
(some enviroments information)

**My test case,**
single url 
![1414](https://user-images.githubusercontent.com/13212227/80703413-b417ea00-8b1d-11ea-902e-0329979e94bc.png)

sing url pipeline (your case)
![415](https://user-images.githubusercontent.com/13212227/80703408-afebcc80-8b1d-11ea-8243-45c40e1cfade.png)

sing url pipeline (your case , Is it because of the special text?)
![1416](https://user-images.githubusercontent.com/13212227/80703418-b5491700-8b1d-11ea-8400-fe5b7fd82772.png)

**Comment by hahwul** [comment]
Oh, I had a similar case during the test. It happens intermittently when mass scanning with a pipe. given the fact that the cause point is StaticAnalysis, it seems to be a problem or a problem where the packet is sent. First, I'll cross-check

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1384679]

goroutine 242538 [running]:
github.com/hahwul/dalfox/pkg/scanning.StaticAnalysis(0xc000215b80, 0x48, 0xc0001133e0, 0x1c)
	/Users/hahwul/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:424 +0x89
github.com/hahwul/dalfox/pkg/scanning.Scan.func1(0xc00002ac80, 0xc0001133e0, 0xc000215b80, 0x48, 0xc00044e028)
	/Users/hahwul/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:74 +0xa3
created by github.com/hahwul/dalfox/pkg/scanning.Scan
	/Users/hahwul/go/src/github.com/hahwul/dalfox/pkg/scanning/scan.go:71 +0x358
```

**Comment by hahwul** [comment]
@ceylanb 
Hi bro! 
Is it being recurrence now? The current version is 1.1.0.

**Comment by ceylanb** [comment]
@hahwul thanks, the problem is solved. Thanks.
