### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by subhash0x** [hahwul/dalfox#69]
why it is scanning 404 response code URL is there any way to skip this

**Comment by hahwul** [comment]
This is because XSS can work well enough in URLs that contain error codes. For example, in the case of custom error page, sometimes there is an XSS pointing in 404. 

As you said, it would be good to create an option to exclude certain return codes when scanning. I'll add that option soon. thank you!

https://github.com/hahwul/dalfox/issues/70

**Comment by hahwul** [comment]
@subhash0x 
If you have any good ideas for the option name, share them with me!
