### ISSUE TITLE
Feature Proposal! - "show amount of urls scanned out of total amount of given urls trough url file list in output terminal"

### ISSUE THREAD

**Issue by Slowpoke079** [hahwul/dalfox#80]
Feature Proposal! - "show amount of urls scanned out of total amount of given urls trough url file list in output terminal"

Why?
I love your tool, and sometimes i am scanning 10000+ links (don't ask). BUT, when scanning i only see the output of the tool testing parameters and XSS found etc.

I would love to have a counter that displays how much urls are scanned and how much still need to be scanned. Example:
i have 100 *.example.com links in a list scan file. I point dalfox to the file and start scanning. [progress: 2/100]

I love Dalfox and XSpear btw ;), let me know what you think about the feature. I could code it for you maybe but i have Zer0 Golang expirience yet... :p

**Comment by hahwul** [comment]
Hi @Slowpoke079 
Thank you for your opinion. I preparing for the next version now, and i'll include it😉
I thought the current log output method was insufficient in many URL modes such as pipe, file mode.

Thank you so much for your good opinion!

**Comment by Slowpoke079** [comment]
Thank you! Much appreciated.

Btw, im a new/newby bugbounty hunter, is there a channel (like discord) where i can ask you things regarding encoded XSS attacks? I recently found one (with dalfox) but i don't know how to get the "alert poc" to work since i do not know how to read encoded payloads for shit.

[V] Reflected Payload in JS: page=';this['x65x76x61x6c']('this['x61x6cx65x72x74'](this['x61x74x6fx62']('WFNT'))');//
    94 line:  ","query":{"page":"2';this['x65x76x61x6c']('this['x61x6cx65x72x74'](this['x61x74
    +> https://somewebsite.com/somepage?page=2%27%3Bthis%5B%27x65x76x61x6c%27%5D%28%27this%5B%27x61x6cx65x72x74%27%5D%28this%5B%27x61x74x6fx62%27%5D%28%27WFNT%27%29%29%27%29%3B%2F%2F

**Comment by hahwul** [comment]
1) Dev logs
First of all, it is reflected in the current code version. It's going to be distributed in a 2.0 release. 
=> 300f231 , and change spinner format
![1414](https://user-images.githubusercontent.com/13212227/89553372-64e20380-d848-11ea-8dd1-ed1de81e462a.png)

2) Question
I don't know which channel to recommend because I'm not participating in channels like discord. Why don't you DM to Awesome guys like BruteLogic with masked information with test code?

If you really don't know how, DM me (with masked. your information is important!). I don't know if it'll help, but I'll check.

**Comment by Slowpoke079** [comment]
Oh i didn't see that! I am dyslexic ,(hi dyslexic) and tend to read over things quite fast when not concentrated... And thanks for all the help! I won't ask to take more time from you since that would be selfish on my side. The tool already does a lot for me <3. And i am waaay to shy for twitter and the like :P.

Thanks for the commitment :)
