### ISSUE TITLE
conflict in readme in blind xss !

### ISSUE THREAD

**Issue by Sy3Omda** [hahwul/dalfox#94]
Hi,
i see in README file that u mentioned if i want to run ```Single target mode``` i will use following code
```$ dalfox url http://testphp.vulnweb.com/listproducts.php\?cat\=123\&artist\=123\&asdf\=ff -b https://hahwul.xss.ht```
BUT in the main [https://github.com/hahwul/dalfox#usage](url) you wrote ```-b, --blind string            Add your blind xss (e.g -b hahwul.xss.ht)```

So which one is correct when i want to use blind xss argument (with http(s) OR without )

**Comment by hahwul** [comment]
Hi @Sy3Omda 
They're both right. They're bifurcating from the inside, so it doesn't really matter :D

```go
if strings.HasPrefix(options.BlindURL, "https://") || strings.HasPrefix(options.BlindURL, "http://") {
    bcallback = options.BlindURL
} else {
    bcallback = "//" + options.BlindURL
}
```
from https://github.com/hahwul/dalfox/blob/master/pkg/scanning/scan.go#L258

However, I think `-b your.xss.ht` is better because i'm not sure whether blind xss is http, https or not in the triggered domain.
Why? protocol-relative URL (PRURL) is the method for linking to a website that offers both HTTP and HTTPS.

I hope it helps.
Cheers :D
