### ISSUE TITLE
Dose this is ready to go ? > e.g in my mind

### ISSUE THREAD

**Issue by Sy3Omda** [hahwul/dalfox#96]
> e.g in my mind
> 
> ```
> --level 1 => reflected path / query / body
> --level 2 => reflected path / query / body and all headers
> --level 3 => all path / query / body / all headers
> ```

AND that would be great.
btw i tried reach u in twitter for quick idea sharing but u DMs looks busy .
anyway as u know some platform grep some header for analyst for different reasons and in that case we could hunt for some blind xss in header.
my last Q is .
what is the different BW dalfox AND XSpear and why two tools serving the same purpose?

_Originally posted by @Sy3Omda in https://github.com/hahwul/dalfox/issues/78#issuecomment-653101951_

**Comment by hahwul** [comment]
Hi @Sy3Omda ,
Besides blind xss, I know the importance of testing header-based XSS even  because using header xss for http request smugling or cache poisoning. 

Header testing isn't just something add. For this, basically, it is necessary to discovery the header like param minor, and it is necessary to consider how to apply it. So first I just added them for header testing on blind xss. (2.0.0  later)

Didn't you answer the last question before? Dalfox is xspear's next project, and it's a full-change tool for performance and diversity. 
(xspear is not ci/cd friendly and is not suitable for pipelines)

|                   | DalFox                                                       | Xspear                                                       |
| ----------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| Language          | go                                                           | ruby                                                         |
| package           | go, homebrew, snap, docker, gitdocker, git-action(making.. on private repo) | gem                                                          |
| Scanning method   | testing reflected or all parameter, and parameter analysis and optimizing test query | testing reflected or all parameter, and parameter analysis   |
| Verify method     | verify with DOM parse (fast, but it's not accurate)          | verify with selenium (very slow and very accurate (by detecting direct alerts). |
| Worker            | Concurrency with goroutine                                   | Multi thread                                                 |
| Maintain project? | Yes,                                                         | Yes, but just a bug fix                                      |
| Report            | text, json                                                   | text, html                                                   |
| API               | Yes                                                          | No                                                           |
| Advantage         | Fast, Friendly pipeline/cicd, many testing options           | High accuracy of results                                     |
| Weakness          | There may be false positive because selenium is not used.    | Very slow, Poor features, weak support                       |

## Conclustion
- I'm thinking about supporting header testing on all sections of the tool. However, speed is important for Dalfox, so I looking for a suitable compromise.
- Dalfox is a more progressive and much better tool. It's a high-quality product better than xspear.

Any question? 😉

**Comment by Sy3Omda** [comment]
Good morning my friend ,
first of all i'm sorry for reference wrong link what i mean was
_Originally posted by @hahwul in https://github.com/hahwul/dalfox/issues/78#issuecomment-653093749_
as per this thought of you i was asking dose this feature will come soon to dalfox ?
i don`t mean here to mention the xpear .

**Comment by hahwul** [comment]
Oh, I understand it
for 2.0.0 , I've only added it to the referrer header 😢.

```go
for _, bpayload := range bpayloads {
    // header base blind xss
    bp := strings.Replace(bpayload, "CALLBACKURL", bcallback, 10)
    tq, tm := optimization.MakeHeaderQuery(target,"Referer",bp,options)
    tm["payload"] = "toBlind"
    query[tq] = tm
}
```

Since I'll try to apply the level flag, there are more things to consider than I thought.. If I think about it and prepare, I think it can be included in the next minor update.

**Comment by Sy3Omda** [comment]
@hahwul good to hear that, in the meanwhile i could send requests with any tool with custom header and payload of xsshunter for possible blind xss
