### ISSUE TITLE
add payloads

### ISSUE THREAD

**Issue by drown95** [hahwul/dalfox#97]
How to add payloads? not accurate results for basic payloads cant show results.. thanks

**Comment by drown95** [comment]
i have a vulnerable test site and my payload is </script><script>alert(1)</script> i try to scan but no result and scan finish..

**Comment by hahwul** [comment]
Hi @drown95 ,
First of all, using custom payloads are available with the `--custom-payload` option.

```
 --custom-payload string   Add custom payloads from file
```
e.g
```shell
$ dalfox url http://testphp.vulnweb.com/listproducts.php\?cat\=123\&artist\=123\&asdf\=ff --custom-payload ~/HAHWUL/tool/dalfox/samples/sample_custompayload.txt
```

And for second question, Do you have any examples? Whether the vulnerability operating in the actual browser does not appear in the tool, it occurs due to differences in cookie/header/HTTP settings (e.g. follow redirect). First of all, I think you need to figure out exactly what kind of problem it is.

- Does it print in the log as Reflected?
```
e.g
[I] Reflected cat param => inHTML[1]   $
    48 line:  	Error: Unknown column '123DalFox' in 'where cl
```
- Isn't it the same even after setting cookies/headers when triggering the browser?
```
  -H, --header string           Add custom headers
  -C, --cookie string           Add custom cookie
        --user-agent string       Add custom UserAgent
        --delay int               Milliseconds between send to same host (1000==1s)
        --follow-redirects        Following redirection
        --timeout int             Second of timeout (default 10)
```

**Comment by drown95** [comment]
oh thank you.. :)

**Comment by hahwul** [comment]
@drown95 
If you have any more questions, submit them as an issue. You're always welcome :D
